@baseUrl = http://localhost:3000

# Messages

###
# @name GetAllMessages
GET {{baseUrl}}/messages?limit=15&offset=5

###
# @name GetOneMessage
GET {{baseUrl}}/messages/1

###
# @name PostOneMessage
POST {{baseUrl}}/messages
Content-Type: application/json

{
    "content": "This is a new message!",
    "from": "John",
    "to": "Doe"
}

###
# @name UpdateOneMessage
PATCH {{baseUrl}}/messages/4
Content-Type: application/json

{
    "content": "This is a updated message!",
    "from": "John",
    "to": "Doe",
}

###
# @name RemoveOneMessage
DELETE {{baseUrl}}/messages/2